name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Verify Docker Compose installation
      run: docker-compose version

    - name: Copy .env.example to .env
      run: cp ./env.example ./env

    - name: Install dependencies
      run: |
        cd ./
        npm install

    - name: List files in the repository
      run: ls -l 

    - name: Grant execute permission to the script
      run: chmod +x ./__test__/integrationTest/scripts/run-integration.sh && chmod +x ./__test__/integrationTest/scripts/wait-for-it.sh

    - name: Run unit test
      run: npm run test:unit-test
    
    - name: Run integration tests
      run: npm run test:integration-test
